version: '3'

services:
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: "edx.devstack.mysql"
    hostname: mysql.devstack.edx
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.7
    logging:
      driver: none
    networks:
      default:
        aliases:
          - edx.devstack.mysql
    ports:
      - "3506:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    container_name: "edx.devstack.mongo"
    hostname: mongo.devstack.edx
    image: mongo:${MONGO_VERSION:-3.6.17}
    logging:
      driver: none
    networks:
      default:
        aliases:
          - edx.devstack.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  edxapp:
    command: bash -c 'source /edx/app/edxapp/venvs/edxapp/bin/activate && paver test_system -s lms --disable_capture'
    build:
      context: .
      dockerfile: Test.Dockerfile
    environment:
      EDXAPP_TEST_MONGO_HOST: edx.devstack.mongo
      NO_PYTHON_UNINSTALL: 1
    depends_on:
      - mysql
      - mongo

volumes:
  mongo_data:
  mysql_data:
