# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/edx-platform

    steps:
      - checkout

      - run:
          name: Prepare Environment
          command: |
            sudo apt-get -y install libxmlsec1-dev libxml2-dev libxslt-dev graphviz libgraphviz-dev libreadline7 libreadline-dev default-libmysqlclient-dev libsqlite3-dev build-essential libgeos-dev mongodb-server mongodb-clients
            sudo pip install virtualenv
            virtualenv -p python venv
            source venv/bin/activate
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v8.9.3
            npm install
            pip install setuptools
            pip install --exists-action w -r requirements/edx/testing.txt
            pip install coveralls==1.0
            pip freeze
      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            sudo mongod --config /etc/mongodb.conf &
            paver test_system -t openedx/features/ucsd_features/tests/tests.py --fasttest
      - store_artifacts:
          path: test-reports
          destination: test-reports

