name: Identify

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  identify_migrations:
    name: identify migrations
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]
        # 'pinned' is used to install the latest patch version of Django
        # within the global constraint i.e. Django==3.2.21 in current case
        # because we have global constraint of Django<4.2
        django-version: ["4.2"]
        mongo-version: ["4"]
        mysql-version: ["8"]
        # excluding mysql5.7 with Django 4.2 since Django 4.2 has
        # dropped support for MySQL<8
        exclude:
          - django-version: "4.2"
            mysql-version: "5.7"
    services:
      mongo:
        image: mongo:${{ matrix.mongo-version }}
        ports:
          - 27017:27017
        # Note: Calling mongo here only works with mongo 4, in newer versions of mongo
        # we'll have to use `mongosh`
        options: >-
          --health-cmd "mongo --quiet --eval 'db.runCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: "edxapp"
          MYSQL_USER: "edxapp001"
          MYSQL_PASSWORD: "password"
          MYSQL_RANDOM_ROOT_PASSWORD: true
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
    - name: Setup mongodb user
      run: |
        mongosh edxapp --eval '
          db.createUser(
            {
              user: "edxapp",
              pwd:  "password",
              roles: [
                   { role: "readWrite", db: "edxapp" },
              ]
            }
          );
        '

    - name: Verify mongo and mysql db credentials
      run: |
        mysql -h 127.0.0.1 -uedxapp001 -ppassword -e "select 1;" edxapp
        mongosh --host 127.0.0.1 --username edxapp --password password --eval 'use edxapp; db.adminCommand("ping");' edxapp

    - name: Checkout master repo
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system Packages
      run: |
        sudo apt-get update
        make ubuntu-requirements

    - name: Get pip cache dir
      id: pip-cache-dir
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/development.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        make dev-requirements
        if [[ "${{ matrix.django-version }}" != "pinned" ]]; then
          pip install "django~=${{ matrix.django-version }}.0"
          pip check # fail if this test-reqs/Django combination is broken
        fi

    - name: Run migrations on master branch
      shell: bash
      env:
        LMS_CFG: lms/envs/minimal.yml
        STUDIO_CFG: lms/envs/minimal.yml
      run: |
        ./manage.py lms showmigrations > ${{ github.workspace }}/abcd.txt

    - name: Checkout your branch repo
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        make dev-requirements
        if [[ "${{ matrix.django-version }}" != "pinned" ]]; then
          pip install "django~=${{ matrix.django-version }}.0"
          pip check # fail if this test-reqs/Django combination is broken
        fi

    - name: list installed package versions
      run: |
        pip freeze

    - name: Run migrations on test branch
      shell: bash
      env:
        LMS_CFG: lms/envs/minimal.yml
        STUDIO_CFG: lms/envs/minimal.yml
      run: |
        ./manage.py lms showmigrations > ${{ github.workspace }}/def.txt


    - name: Debug File Paths
      run: |
        ls -R ${{ github.workspace }}


    - name: Process Data
      run: |
        FILE1_PATH="${{ github.workspace }}/def.txt"
        FILE2_PATH="${{ github.workspace }}/abcd.txt"

        # Fetch the content of the files
        FILE1_CONTENT=$(cat $FILE1_PATH)
        FILE2_CONTENT=$(cat $FILE2_PATH)
        git diff --no-index --color-words $FILE1_PATH $FILE2_PATH
      shell: bash

#    - name: Comment PR
#      uses: thollander/actions-comment-pull-request@v2
#      with:
#        filePath:  cleaned_data.txt
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
