on: [pull_request]
name: 'Merge conflicts'

jobs:
  report_master:
    name: 'master'
    uses: appsembler/action-conflict-counter/.github/workflows/report-via-comment.yml@main
    with:
      local_base_branch: ${{ github.base_ref }}
      upstream_repo: 'https://github.com/edx/edx-platform.git'
      upstream_branch: 'master'
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}

  report_koa:
    name: 'koa'
    uses: appsembler/action-conflict-counter/.github/workflows/report-via-comment.yml@main
    with:
      local_base_branch: ${{ github.base_ref }}
      upstream_repo: 'https://github.com/edx/edx-platform.git'
      upstream_branch: 'open-release/koa.master'
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
