name: Upgrade Requirements

on:
  schedule:
     - cron: "0 2 * * 2"
  workflow_dispatch:
     inputs:
       branch:
         description: 'Target branch to create requirements PR against'
         required: true
         default: 'master'
jobs:
   call-upgrade-python-requirements-workflow:
    with:
       branch: ${{ github.event.inputs.branch }}
       team_reviewers: "arbi-bom"
       email_address: arbi-bom@edx.org
       send_success_notification: false
    secrets:
       requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
       requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
       edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
       edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
    uses: openedx/.github/.github/workflows/upgrade-python-requirements.yml@master

