name: verify unit tests count

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  collect-and-verify:
    if: (github.repository == 'edx/edx-platform-private') || (github.repository == 'openedx/edx-platform' && (startsWith(github.base_ref, 'open-release') == false))
    runs-on: [ "ubuntu-20.04" ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install system requirements
        run: |
          make ubuntu-requirements

      - name: install requirements
        run: |
          sudo env "PATH=$PATH" make test-requirements

      - name: verify unit tests count
        uses: ./.github/actions/verify-tests-count
